from odoo import http
from odoo.http import request
from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from io import BytesIO
from datetime import datetime


class WordSoldPropertyReport(http.Controller):
    @http.route('/property/word/sold/report', type='http', auth='user', methods=['GET'], csrf=False)
    def download_sold_property_word_report(self):
        # جلب كل العقارات المباعة فقط
        sold_properties = request.env['property'].search([('state','=','sold')])
        today_str = datetime.today().strftime('%d/%m/%Y')  # يحول تاريخ اليوم إلى 'يوم/شهر/سنة'

        document = Document()
        title = document.add_paragraph('Property Report Word', style='Title')
        title.alignment = 1  # Center - خلي العنوان يتنسق ليكون في النص -
        date_para = document.add_paragraph(f'Date: {today_str}', style='Normal')
        date_para.alignment = 1  # Center - خلي العنوان يتنسق ليكون في النص -

        # إنشاء جدول
        table = document.add_table(rows=1, cols=2)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        table.style = 'Table Grid'

        # Header
        hdr_cells = table.rows[0].cells
        headers = ['Name', 'Selling Price']
        for i, header in enumerate(headers):
            hdr_cells[i].text = header

        # البيانات
        for prop in sold_properties:
            row_cells = table.add_row().cells
            row_cells[0].text = str(prop.name)
            row_cells[1].text = f"${prop.selling_price:,.2f}"

        spase = document.add_paragraph('', style='Normal')
        spase.alignment = 1  # Center
        footer = document.add_paragraph('Generated by Odoo', style='Normal')
        footer.alignment = 1  # Center

        # حفظ الملف في الذاكرة
        output = BytesIO()
        document.save(output)
        output.seek(0)


        return request.make_response(

            output.getvalue(),
            headers=[
                ('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'),
                ('Content-Disposition', 'attachment; filename=Sold_Property_Report.docx')
            ]
        )
